cluster.name: "{{ os_cluster_name }}"

node.name: "{{ inventory_hostname }}"

path.data: "{{ os_data_dir }}"
path.logs: "{{ os_logs_dir }}"

network.host:
- 127.0.0.1
- "{{ hostvars[inventory_hostname]['ip'] }}"

http.port: 9200

bootstrap.memory_lock: true

discovery.seed_hosts: ["{{ os_nodes }}"]

cluster.initial_master_nodes: ["{{ os_master_nodes }}"]

node.roles: [{{ hostvars[inventory_hostname]['roles'] }}]
